# this file's inspiration: https://github.com/paulalden/dotfiles/tree/main/tmux

# ┌────────────────────────────────────┐
# │               Setup                │
# └────────────────────────────────────┘

tmux_dir="~/.config/tmux"
tmux_conf_dir="${tmux_dir}/config"

# ┌────────────────────────────────────┐
# │           Configuration            │
# └────────────────────────────────────┘

source "${tmux_conf_dir}/options.conf"
source "${tmux_conf_dir}/keybindings.conf"
source "${tmux_conf_dir}/theme.conf"
#source "${tmux_conf_dir}/theme-evergreen.conf"
#source "${tmux_conf_dir}/theme-2049.conf"


